- name: type/bug
  from_name: bug
- name: status/duplicate
  from_name: duplicate
- name: type/enhancement
  from_name: enhancement
- name: type/help-needed
  from_name: help wanted
- name: status/invalid
  from_name: invalid
- name: type/question
  from_name: question
- name: status/declined
  from_name: wontfix
- name: type/task
  from_name: task
- name: area/tests
  from_name: test
- name: area/jepsen
  from_name: jepsen
- name: area/documentation
  from_name: docs
- name: for/backport
  from_name: backport
- name: type/epic
  from_name: Epic
- name: area/dependencies
  from_name: dependencies
- name: for/blocker
  from_name: blocker
